### ISSUE TITLE
Scatterplot notebook: test_model.compute_averages affects model.initial_states

### ISSUE THREAD

**Issue by ibestvina** [sphinxteam/sir_inference#4]
Notebook [Scatterplot_mean_field_dmp](https://github.com/sphinxteam/sir_inference/blob/master/Scatterplot_mean_field_dmp.ipynb) uses the model instance two times (for two scatterplot sets) to generate `initial_probas`. However, initial state of the model is changed to a random state in the first run because `generate_scatterplot` calls `compute_averages` which sets the initial states to random. 

This might make the two scatterplot sets incomparable (I am not sure about this, haven't fully read through the code, just noticed this inconsistency).

**Comment by antoinebaker** [comment]
Yes, the two scatterplots are two independent tests. But the goal here is only to check that  DMP/mean field agree with the Monte Carlo frequencies.

**Comment by ibestvina** [comment]
But the DMP is never in this notebook tested on the initial states that were set in the beginning of the notebook - they are always only tested on the random initial states.

Correctly predicting state probabilities in case of a single patient zero and in case of a uniform random initial state are two quite different tasks, aren't they?

**Comment by antoinebaker** [comment]
It should not matter much for checking the probas estimation, just the frequencies/probabilties will be less evenly spread out. I will add these cases to be sure.

**Comment by antoinebaker** [comment]
The model.initial_states is no longer overwritten to generate the scatterplot ea699df
You can now choose the initial_states, eg see the Scatterplot notebook.
